repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        name: "ruff lint"
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
      - id: ruff-format
        name: "ruff format"
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
    - id: bandit
